### ISSUE TITLE
Rejects passwords

### ISSUE THREAD

**Issue by haarp** [evgeny-gridasov/openvpn-otp#12]
Hello,

I'm trying to set this up on pfSense. I managed to get it compiled and loaded, but all I'm ever getting are failed authentications. Is there some way to increase log verbosity so I can see what's going on? It would be very useful if this plugin could log (temporarily) what passwords it expects and which ones it receives.

Thanks!

**Comment by evgeny-gridasov** [comment]
This is what I actually wanted to implement some time later.. may be it is the time to do it now. I'll see what I can do.

**Comment by calve** [comment]
Didn't pfSense comes bundle with SELinux ? In which case you may read https://github.com/evgeny-gridasov/openvpn-otp#selinux

**Comment by haarp** [comment]
@calve pfSense is based on FreeBSD

**Comment by calve** [comment]
You can try adding something like 
``LOG("expected %s read %s", secret, vpn_secret);`` around https://github.com/evgeny-gridasov/openvpn-otp/blob/master/src/otp.c#L410

**Comment by kobuki** [comment]
Same issue here. No totp passwords are accepted at all. Cross-checked mobile-generated 6-digit codes with ones generated on the server. They always match. With or without pin, doesn't work at all.

**Comment by evgeny-gridasov** [comment]
Implemented debug mode in 0d6099e
Add debug=1 to your settings to turn debug mode on.

**Comment by bbrendon** [comment]
@haarp how did you get this to compile on pfsense? Can you provide some guidance? I've been trying on freebsd thinking I can copy it to pfsense : https://github.com/evgeny-gridasov/openvpn-otp/issues/18
