### ISSUE TITLE
Extended Setup Process for the Google Authenticator Package

### ISSUE THREAD

**Issue by aioue** [evgeny-gridasov/openvpn-otp#17]
Have modified an existing OpenVPN install and followed the install process for `openvpn-otp`.

How do I generate values for the `opt-secrets` "key" (token?), and how do I link it to Google Authenticator on my phone?

Would like to use "sha1/base32 for Google Authenticator with a simple pin".

**Comment by aioue** [comment]
Solved:

- install `google-authenticator`
- run `google-authenticator --time-based --disallow-reuse --force --rate-limit=3 --rate-time=30 --window-size=17 --issuer=foocorp --label=user@hostname --secret=/root/.user.google_authenticator > /root/user.auth`
- `user.auth` file will contain the key for entry into `opt-secrets`, and the Google URL containing the image to be scanned with authenticator

Running the same command without redirecting it will produce an QR code on the command line. I cannot work out how to capture that though. Anyone?

Would you accept a PR containing the above?

**Comment by ptonewreckin** [comment]
@aioue You should be able to capture the QR code with the Google Authenticator app. Open app, click '+', and scan barcode

**Comment by evgeny-gridasov** [comment]
@aioue Please send me a pull request and I'll accept it

**Comment by aioue** [comment]
https://github.com/evgeny-gridasov/openvpn-otp/pull/19

**Comment by evgeny-gridasov** [comment]
Done. Sorry for the delay
