### ISSUE TITLE
Client compatibility

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [evgeny-gridasov/openvpn-otp#2]
This looks really interesting!
Before I upgrade my server though, I would like to know:
Does each client have to support this login method specifically or is it delivered through a generic password prompt? 
I access my server via the openvpn android app a lot so this would need to be compatible for me.
Thanks for clarifing!

**Comment by evgeny-gridasov** [comment]
You need to make sure that reneg_sec is set to 0 on your client. Other than that everything else should just work. You'll get a generic password prompt on the client.
When asked, provide your username and a password. Your password is a concatenation of the PIN and current OTP token, for a PIN=1234 and token=777888 you should enter 1234777888

**Comment by 1337sup3rh4x0r** [comment]
due to the rather weak 4 digit pin, is this combination not weaker than a strong password on its own?

**Comment by evgeny-gridasov** [comment]
I am not a crypto expert but this combination is very common in many enterprise production environments.

**Comment by jayeye** [comment]
Given that people usually tape the PIN on the fob itself, it indeed does not increase security. The usual reason for having a PIN is to guard against using the wrong fob and then complaining to the IT staff that their fob is not working.

**Comment by evgeny-gridasov** [comment]
1337sup3rh4x0r - restriction on the PIN has been removed, from now on it may be an  arbitrary string or even empty if you want.
