### ISSUE TITLE
Compatible with user key files

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [evgeny-gridasov/openvpn-otp#3]
I managed to install this plugin to my server but now I cannot log in while it is enabled. Could it be that otp does not work alongside with user key files?

Or maybe I am doing something wrong with the google auth key.
I understand from the readme, that in the /etc/ppp/otp-secrets file the key needs to be put in base32 format.
What about in the google auth app? base32 or plain?
Also, does the key need to have a specific length?

**Comment by evgeny-gridasov** [comment]
I think when you switch it to username/password mode it stops working with .key files.
base32 should go both in google authenticator and openvpn-otp
The length is standard google auth key length which is 16 characters of base32
Use google-authenticator cli tool to generate them and then scan generated QR code with the mobile phone app.

**Comment by 1337sup3rh4x0r** [comment]
Thank you for clearifying! Maybe it would help others to get startet if this was in the Readme?

**Comment by maxadamo** [comment]
what do you mean by "key file"? I use ca.crt + client.crt + client.key + OTP, and everything is working like a charm.
