### ISSUE TITLE
OTP-AUTH: authentication failed for username 'xxxx'

### ISSUE THREAD

**Issue by feeman89** [evgeny-gridasov/openvpn-otp#38]
![image](https://user-images.githubusercontent.com/65520943/106265183-9ec51d00-6261-11eb-9526-4a9b70b6b654.png)

why

**Comment by feeman89** [comment]
why i use opt auth, it throw OTP-AUTH: authentication failed for username 'xxxx'  error ?

**Comment by evgeny-gridasov** [comment]
Hello, feeman89,

Have you verified that time is synchronised on the server and that your soft/hard token produces same result as the `oathtool` utility on the server?

**Comment by feeman89** [comment]
thanks , very much ,my time is not sync , thank you very much!!!!
